server:
  host: ""
  port: ""

database:
  host: ""
  port: ""
  user: ""
  password: ""
  name: ""

nats-streaming:
  url: ""
  cluster_id: ""
  client_id: ""

redis:
  url: ""
  password: ""
  DB: 0
